kind: Service
apiVersion: v1
metadata:
  name: "storeserver"
spec:
  selector:
    app: "storeserver"
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
    protocol: "TCP"
  type: LoadBalancer
  loadBalancerIP: 146.148.48.2 # upspin-test
