#!/bin/bash
openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
	-keyout key.pem -out cert.pem \
	-subj "/CN=localhost" \
	-extensions EXT -config <( \
	printf "[dn]\nCN=localhost\n[req]\ndistinguished_name=dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
