// Code generated by protoc-gen-go.
// source: store.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	store.proto

It has these top-level messages:
	Endpoint
	Location
	GetRequest
	GetResponse
	PutRequest
	PutResponse
	DeleteRequest
	DeleteResponse
	ConfigureRequest
	ConfigureResponse
	EndpointRequest
	EndpointResponse
	ServerUserNameRequest
	ServerUserNameResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

// Endpoint mirrors upspin.Endpoint.
type Endpoint struct {
	Transport int32  `protobuf:"varint,1,opt,name=transport" json:"transport,omitempty"`
	NetAddr   string `protobuf:"bytes,2,opt,name=net_addr,json=netAddr" json:"net_addr,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto1.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Location mirrors upspin.Location.
type Location struct {
	Endpoint  *Endpoint `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	Reference string    `protobuf:"bytes,2,opt,name=reference" json:"reference,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto1.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type GetRequest struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetResponse struct {
	Data      []byte      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Locations []*Location `protobuf:"bytes,2,rep,name=locations" json:"locations,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetResponse) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type PutRequest struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto1.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PutResponse struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto1.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteRequest struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ConfigureRequest struct {
	Options []string `protobuf:"bytes,1,rep,name=options" json:"options,omitempty"`
}

func (m *ConfigureRequest) Reset()                    { *m = ConfigureRequest{} }
func (m *ConfigureRequest) String() string            { return proto1.CompactTextString(m) }
func (*ConfigureRequest) ProtoMessage()               {}
func (*ConfigureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ConfigureResponse struct {
}

func (m *ConfigureResponse) Reset()                    { *m = ConfigureResponse{} }
func (m *ConfigureResponse) String() string            { return proto1.CompactTextString(m) }
func (*ConfigureResponse) ProtoMessage()               {}
func (*ConfigureResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type EndpointRequest struct {
}

func (m *EndpointRequest) Reset()                    { *m = EndpointRequest{} }
func (m *EndpointRequest) String() string            { return proto1.CompactTextString(m) }
func (*EndpointRequest) ProtoMessage()               {}
func (*EndpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type EndpointResponse struct {
	Endpoint *Endpoint `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *EndpointResponse) Reset()                    { *m = EndpointResponse{} }
func (m *EndpointResponse) String() string            { return proto1.CompactTextString(m) }
func (*EndpointResponse) ProtoMessage()               {}
func (*EndpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *EndpointResponse) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type ServerUserNameRequest struct {
}

func (m *ServerUserNameRequest) Reset()                    { *m = ServerUserNameRequest{} }
func (m *ServerUserNameRequest) String() string            { return proto1.CompactTextString(m) }
func (*ServerUserNameRequest) ProtoMessage()               {}
func (*ServerUserNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type ServerUserNameResponse struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *ServerUserNameResponse) Reset()                    { *m = ServerUserNameResponse{} }
func (m *ServerUserNameResponse) String() string            { return proto1.CompactTextString(m) }
func (*ServerUserNameResponse) ProtoMessage()               {}
func (*ServerUserNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto1.RegisterType((*Endpoint)(nil), "proto.Endpoint")
	proto1.RegisterType((*Location)(nil), "proto.Location")
	proto1.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto1.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto1.RegisterType((*PutRequest)(nil), "proto.PutRequest")
	proto1.RegisterType((*PutResponse)(nil), "proto.PutResponse")
	proto1.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto1.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
	proto1.RegisterType((*ConfigureRequest)(nil), "proto.ConfigureRequest")
	proto1.RegisterType((*ConfigureResponse)(nil), "proto.ConfigureResponse")
	proto1.RegisterType((*EndpointRequest)(nil), "proto.EndpointRequest")
	proto1.RegisterType((*EndpointResponse)(nil), "proto.EndpointResponse")
	proto1.RegisterType((*ServerUserNameRequest)(nil), "proto.ServerUserNameRequest")
	proto1.RegisterType((*ServerUserNameResponse)(nil), "proto.ServerUserNameResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Store service

type StoreClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	Endpoint(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*EndpointResponse, error)
	ServerUserName(ctx context.Context, in *ServerUserNameRequest, opts ...grpc.CallOption) (*ServerUserNameResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/proto.Store/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/proto.Store/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/proto.Store/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	out := new(ConfigureResponse)
	err := grpc.Invoke(ctx, "/proto.Store/Configure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Endpoint(ctx context.Context, in *EndpointRequest, opts ...grpc.CallOption) (*EndpointResponse, error) {
	out := new(EndpointResponse)
	err := grpc.Invoke(ctx, "/proto.Store/Endpoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) ServerUserName(ctx context.Context, in *ServerUserNameRequest, opts ...grpc.CallOption) (*ServerUserNameResponse, error) {
	out := new(ServerUserNameResponse)
	err := grpc.Invoke(ctx, "/proto.Store/ServerUserName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Store service

type StoreServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	Endpoint(context.Context, *EndpointRequest) (*EndpointResponse, error)
	ServerUserName(context.Context, *ServerUserNameRequest) (*ServerUserNameResponse, error)
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Endpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Endpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/Endpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Endpoint(ctx, req.(*EndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_ServerUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).ServerUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Store/ServerUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).ServerUserName(ctx, req.(*ServerUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Store_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Store_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Store_Delete_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Store_Configure_Handler,
		},
		{
			MethodName: "Endpoint",
			Handler:    _Store_Endpoint_Handler,
		},
		{
			MethodName: "ServerUserName",
			Handler:    _Store_ServerUserName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0xb7, 0x20, 0xbb, 0xed, 0xab, 0xee, 0xc2, 0xe8, 0x42, 0xad, 0x98, 0x34, 0x73, 0x22,
	0x22, 0x1c, 0x30, 0xc6, 0x93, 0x51, 0x83, 0x86, 0x8b, 0x51, 0x52, 0xc2, 0x99, 0x54, 0xfa, 0x30,
	0x24, 0x30, 0x53, 0x67, 0xa6, 0xfe, 0xe1, 0xfe, 0x05, 0xa6, 0xed, 0x74, 0x5a, 0x0a, 0x1a, 0x3d,
	0xb5, 0x7d, 0xef, 0x33, 0xdf, 0xf7, 0xe3, 0x3b, 0x05, 0x57, 0x2a, 0x2e, 0x70, 0x9a, 0x08, 0xae,
	0x38, 0xe9, 0xe4, 0x0f, 0x3a, 0x07, 0xfb, 0x13, 0x8b, 0x13, 0xbe, 0x67, 0x8a, 0x0c, 0xc1, 0x51,
	0x22, 0x62, 0x32, 0xe1, 0x42, 0x79, 0x56, 0x60, 0x8d, 0x3a, 0x61, 0x15, 0x20, 0x4f, 0xc1, 0x66,
	0xa8, 0x36, 0x51, 0x1c, 0x0b, 0xaf, 0x15, 0x58, 0x23, 0x27, 0xbc, 0x61, 0xa8, 0x3e, 0xc4, 0xb1,
	0xa0, 0x6b, 0xb0, 0x3f, 0xf3, 0x6d, 0xa4, 0xf6, 0x9c, 0x91, 0x31, 0xd8, 0xa8, 0x05, 0x73, 0x0d,
	0x77, 0x76, 0x57, 0x54, 0x9c, 0x96, 0x75, 0x42, 0x03, 0x64, 0x15, 0x05, 0xee, 0x50, 0x20, 0xdb,
	0xa2, 0x16, 0xad, 0x02, 0xf4, 0x05, 0xc0, 0x02, 0x55, 0x88, 0x3f, 0x52, 0x94, 0x0d, 0xd6, 0x6a,
	0xb2, 0x4b, 0x70, 0x73, 0x56, 0x26, 0x9c, 0x49, 0x24, 0x04, 0x1e, 0xc4, 0x91, 0x8a, 0x72, 0xee,
	0x61, 0x98, 0xbf, 0x93, 0x09, 0x38, 0x07, 0xdd, 0xa5, 0xf4, 0x5a, 0x41, 0xbb, 0xd6, 0x5a, 0xd9,
	0x7d, 0x58, 0x11, 0x34, 0x00, 0x58, 0xa6, 0xa6, 0xfa, 0x05, 0x41, 0x3a, 0x06, 0x37, 0x27, 0x74,
	0xcd, 0xbf, 0x37, 0x38, 0x81, 0x47, 0x1f, 0xf1, 0x80, 0x0a, 0xff, 0x6d, 0x9e, 0x2e, 0xdc, 0x96,
	0x78, 0x21, 0x4f, 0x5f, 0x42, 0x77, 0xce, 0xd9, 0x6e, 0xff, 0x3d, 0x15, 0x46, 0xc3, 0x83, 0x1b,
	0x9e, 0x14, 0x03, 0x59, 0x41, 0x3b, 0xb3, 0x44, 0x7f, 0xd2, 0xc7, 0xd0, 0xab, 0xd1, 0x5a, 0xa2,
	0x07, 0x77, 0xc6, 0x84, 0x42, 0x81, 0xbe, 0x83, 0x6e, 0x15, 0xd2, 0x83, 0xfc, 0x8f, 0x85, 0x74,
	0x00, 0xf7, 0x2b, 0x14, 0x3f, 0x51, 0xac, 0x25, 0x8a, 0x2f, 0xd1, 0xb1, 0xec, 0x8d, 0xbe, 0x86,
	0x7e, 0x33, 0xa1, 0xf5, 0x9f, 0x81, 0x93, 0x4a, 0x14, 0x1b, 0x16, 0x1d, 0xcb, 0xc9, 0xed, 0x54,
	0x43, 0xb3, 0x5f, 0x2d, 0xe8, 0xac, 0xb2, 0x7b, 0x4a, 0xa6, 0xd0, 0x5e, 0xa0, 0x22, 0x3d, 0x5d,
	0xbb, 0xba, 0x0a, 0x3e, 0xa9, 0x87, 0xf4, 0x6c, 0x57, 0x19, 0xbf, 0x4c, 0x2b, 0xbe, 0x32, 0xcf,
	0xf0, 0x35, 0xb7, 0xe8, 0x15, 0x79, 0x03, 0xd7, 0xc5, 0x8a, 0xc9, 0x13, 0x9d, 0x3f, 0x31, 0xc8,
	0xbf, 0x6f, 0x44, 0xcd, 0xc1, 0xf7, 0xe0, 0x98, 0xdd, 0x92, 0x81, 0xa6, 0x9a, 0xde, 0xf8, 0xde,
	0x79, 0xc2, 0x28, 0xbc, 0xad, 0xfd, 0x75, 0xfd, 0xe6, 0x6e, 0xf5, 0xf9, 0xc1, 0x59, 0xdc, 0x1c,
	0xff, 0x0a, 0xb7, 0xa7, 0xab, 0x25, 0x43, 0x0d, 0x5f, 0xb4, 0xc2, 0x7f, 0xfe, 0x87, 0x6c, 0x29,
	0xf8, 0xed, 0x3a, 0xcf, 0xbf, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x46, 0xcf, 0x5f, 0x22,
	0x04, 0x00, 0x00,
}
