#!/bin/sh
# Copyright 2017 The Upspin Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
cd cmd/upspin; go install ./...
cd ../upspinfs; go install ./...
cd ../cacheserver; go install ./...
